
version: "3.9"
services:
  front-end:
    container_name: front-end-2
    build: ./template-basic
    ports:
      - "3002:3002"
    environment:
      NEXT_PUBLIC_SN: 2
      SN: 2
      NEXT_PUBLIC_MESSAGE: "good-news"
    command: yarn start -p 3002
  