
version: "3.9"
services:
  front-end-1111:
    build: ./template-basic
    ports:
      - "3003:3003"
    environment:
      - SN=1111
      - NEXT_PUBLIC_SN=1111
      - MESSAGE="good-news"
      - NEXT_PUBLIC_MESSAGE="good-news"
    stdin_open: true
    tty: true
  